import Head from 'next/head'
import Header from '../components/Header'
import HomePage from '../components/HomePage'
import Catalogo from '../components/Catalogo'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Doce Surpresa Cestaria</title>
        <meta name="description" content="Generated by Michael Morais" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet"/>

        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <Header/>
      <HomePage></HomePage>
      <Catalogo text={"Especial Dia das mães"}></Catalogo>
      <Catalogo text={"Café da manhã"}></Catalogo>
      <Catalogo text={"Bolos"}></Catalogo>
      <Catalogo text={"Chocolates"}></Catalogo>
      <Catalogo text={"Petiscos e frios"}></Catalogo>

      <Footer/>
    </>
  )
}
